function [zc,zf] = getmodelgridz(filepath)


% getmodelgridz  Obtains the depths of the cell faces and centers for the
% zgrid.out file
%===================================================================
%
% USAGE:  [zc,zf] = getmodelgridz(filepath)
%
% DESCRIPTION:
%   This function imports the z-levels of the model grid using the zgrid.out
%   file generated by PSOM on the 1st timestep.
%
% INPUT:
%    filepath       = path directory of zgrid.out
%
% OUTPUT:
%    zc         = depth of cell centers in model [in m]
%    zf         = depth of cell faces in model [in m]
%
% AUTHOR:   Mathieu Dever 11-04-2017
%
% UPDATES: 08-12-2017 -- Modified function to extract both cell faces and
% cell centers coordinates
%
% DEPENDENCIES:
%
%==================================================================

%----------------------
% CHECK INPUT ARGUMENTS
%----------------------

if exist(filepath,'file') ~= 2
    error('zgrid.out could not be found. Please make sure the file is in you Current Folder, or include the path directory to the file')
end

%----------------------
% CORE CODE
%----------------------

delimiter = ' ';
startRow = 2;

% Specifies data format
formatSpec = '%s%s%s%[^\n\r]';
% Opens the text file.
fileID = fopen(filepath,'r');
% Reads the data
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
% Closes the text file.
fclose(fileID);

% Flag to know if extracting cell centers or cell faces
cellfaceflag = 0;
counter = 1;
for ii = 1:length(dataArray{1,1})
    if isnan(str2double(dataArray{1,1}{ii,1}))
        % Change flag to extract cell faces depths
        cellfaceflag = 1;
        % Reset the loop counter
        counter = 1;
        % Skips the header for the celle faces part fo the file
        continue
    end
    if cellfaceflag
        zf(counter) = str2double(dataArray{1,2}{ii,1});
    else
        zc(counter) = str2double(dataArray{1,2}{ii,1});
    end
    counter = counter+1;
end; clear ii
end
