function [xc,yc] = getmodelgridxy(filename)

% getmodelgridxy  Gets model horizontal model grid points from output file
%===================================================================
%
% USAGE:  [xc,yc] = getmodelgridxy(filename);
%
% DESCRIPTION:
%   This function imports the grid points of the model grid in the
%   horizontal using the horizontalgrid.out file generated by PSOM on the
%   1st timestep.
%
% INPUT:
%    filename       = path directory of horizontalgrid.out
%
% OUTPUT:
%    xc             = position of cell centers in x-direction [in m]
%    yc             = position of cell centers in y-direction [in m]
%
% AUTHOR:   Mathieu Dever 21-04-2017
%
% REFERENCE:
%
% DEPENDENCIES:
%
%==================================================================

%----------------------
% CHECK INPUT ARGUMENTS
%----------------------

if exist(filename,'file') ~= 2
    error('horizontalgrid.out could not be found. Please make sure the file is in you Current Folder, or include the path directory to the file')
end

%----------------------
% CORE CODE
%----------------------

delimiter = ' ';
startRow = 2;

% Specifies data format
formatSpec = '%s%s%s%[^\n\r]';
% Opens the text file.
fileID = fopen(filename,'r');
% Reads the data
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
% Closes the text file.
fclose(fileID);

myswitch = 0;
for ii = 1:length(dataArray{1,1})
    if isnan(str2double(dataArray{1,1}{ii,1}))
        % Used to determine if extracting x or y
        myswitch = 1;
        continue
    end
    if myswitch == 0
        xc(str2double(dataArray{1,1}{ii,1})+1) = str2double(dataArray{1,2}{ii,1});
    elseif myswitch == 1
        yc(str2double(dataArray{1,1}{ii,1})+1) = str2double(dataArray{1,2}{ii,1});
    end
end; clear ii
end
