#undef  runtracmass
#define periodic_ew
#undef  periodic_ns
#undef  allow_particle
#define rhoonly
#undef  relaxation
#undef  fixed_bottom_thickness
#undef  gotm_call
#undef  implicit
#define file_output
#define file_output_cdf
#undef  file_output_bin
