#undef  runtracmass
#define periodic_ew
#undef  periodic_ns
#define allow_particle
#define rhoonly
#undef  relaxation
#undef  fixed_bottom_thickness
#define file_output
#define file_output_cdf
#define file_output_bin
#undef  gotm_call
#undef  implicit
